version: '3.8'

services:
  db_mysql:
    image: mysql:8.0
    container_name: lua_cosmeticos_db
    restart: always
    environment:
      MYSQL_DATABASE: lua_cosmeticos_db

      # MYSQL_ROOT_PASSWORD: Define a senha do usu√°rio 'root'
      MYSQL_ROOT_PASSWORD: senha_secreta_root

    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - lua_network

volumes:
  mysql_data:

networks:
  lua_network:
